export const CREATE_SONG = 'CREATE_SONG';
export const LOAD_SONGS_SUCCESS = 'LOAD_SONGS_SUCCESS';
export const LOAD_ARTISTS_SUCCESS = 'LOAD_ARTISTS_SUCCESS';
export const UPDATE_SONG_SUCCESS = 'UPDATE_SONG_SUCCESS';
export const CREATE_SONG_SUCCESS = 'CREATE_SONG_SUCCESS';
export const DELETE_SONG = 'DELETE_SONG';

export const UPDATE_ARTIST_SUCCESS = 'UPDATE_ARTIST_SUCCESS';
export const CREATE_ARTIST_SUCCESS = 'CREATE_ARTIST_SUCCESS';
export const DELETE_ARTIST = 'DELETE_ARTIST';
export const CREATE_ARTIST = 'CREATE_ARTIST';
